### PR TITLE
Bug Fix: Fix several listing commands not working

### LINKED ISSUE #244: Bug: Cannot add buyers to listing
image

### LINKED ISSUE #245: Bug: Cannot execute clearlistings
image

### LINKED ISSUE #249: Bug: Cannot execute removelistingbuyers
image

### PR DESCRIPTION
**Pull request by muhdbhz**
Fix #244 
Fix #245  
Fix #249  

Despite failing code coverage (because no new tests were made, just bug fixing), overall coverage went up. Should be OK to merge

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -121,13 +127,12 @@ public Command parseCommand(String userInput) throws ParseException {
...
     private boolean isListingCommand(String commandWord) {
         return commandWord.equals(AddListingCommand.COMMAND_WORD)
-                || commandWord.equals("editListing")
-                || commandWord.equals("addBuyersToListing")
-                || commandWord.equals("deleteListing")
-                || commandWord.equals("clearListings")
-                || commandWord.equals("findListings")
-                || commandWord.equals("listListings")
-                || commandWord.equals("removeBuyersFromListing");
+                || commandWord.equals(EditListingCommand.COMMAND_WORD)
```
Comment (lrongyi) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java:130]: LGTM, good catch
